metadata:
  pipeline_interfaces: pipeline_interface.yaml
  output_dir: $HOME/datadir
  sample_annotation: anno.csv

attributes:
  provider: UCSC
  organism: Homo sapiens
  taxonomy_id: 9606
  
derived_columns: remote_url

data_sources:
  ucsc: http://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/{sample_name}

implied_columns:
  organism:
    human:
      genome: hg19

bioconductor:
  read_fun_name: parseEncodeRegions
  # The read_fun_dir is specific to the machine the BiocProject is run
  # read_fun_path: $HOME/Uczelnia/UVA/example_peps/example_BiocProject/parseEncodeRegions.R
  read_fun_path: parseEncodeRegions.R
