metadata:
  pipeline_interfaces: pipeline_interface.yaml
  output_dir: $HOME/datadir
  sample_annotation: anno.csv

attributes:
  provider: UCSC
  organism: Homo sapiens
  taxonomy_id: 9606
  
derived_columns: remote_url

data_sources:
  ucsc: http://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/{sample_name}

implied_columns:
  organism:
    human:
      genome: hg19

bioconductor:
  read_fun_name: parseEncodeRegions_args
  read_fun_path: parseEncodeRegions_args.R
