metadata:
  sample_annotation: sample_annotation.csv

derived_columns: remote_url

data_sources:
  ucsc: http://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/{sample_name}

bioconductor:
  read_fun_name: parseEncodeRegions_resize
  read_fun_path: parseEncodeRegions_resize.R
