metadata:
  sample_annotation: sample_annotation.csv
  merge_table: merge_table.csv
  output_dir: $HOME/hello_looper_results
  pipeline_interfaces: [../pipeline/pipeline_interface.yaml]

derived_columns: [file]

data_sources:
  local_files: "../data/{identifier}{file_id}_data.txt"
  local_files_unmerged: "../data/{identifier}*_data.txt"